version: '3'
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
  #    volumes:
  #      - db:/var/lib/postgresql/data
  #      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  backend:
    image: backend
    restart: always
    build:
      context: ./backend  # Use the Dockerfile from the backend
    ports:
      - 8080:8000
    volumes:
      - ./backend/src:/home/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: mydb
      FLASK_DEBUG: "true"

    env_file: .env
    command: ["python", "app.py"]
    links:
      - db
    depends_on:
      - db

volumes:
  dbdata:
